name: test

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest pytest-cov
        pip install -r requirements.txt
        pip install -e .
    - name: Create credentials file
      run: |
        mkdir /tmp/btc
        touch /tmp/btc/credentials.json
    - name: Test with pytest
      run: |
        pytest -vv -l --cov=./ --cov-report=xml
      env:
        BTC_ROOT_PATH: /tmp/btc
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
